services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/n8n-io/n8n
    plan: free
    dockerfilePath: docker/images/n8n/Dockerfile

    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: "anton"
      - key: N8N_BASIC_AUTH_PASSWORD
        value: "tusegura123"
      - key: GENERIC_TIMEZONE
        value: "America/Bogota"
      - key: N8N_HOST
        value: "n8n.onrender.com"
      - key: N8N_PORT
        value: "5678"
      - key: N8N_PROTOCOL
        value: "https"
